# Generated by Django 5.2.7 on 2025-10-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id_comprobante', models.IntegerField(primary_key=True, serialize=False)),
                ('nro_comprobante', models.CharField(max_length=50)),
                ('fecha_emision', models.DateTimeField()),
            ],
            options={
                'db_table': 'Comprobante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.IntegerField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'Cuota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanCuotasAlumno',
            fields=[
                ('id_plan', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Plan_Cuotas_Alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id_plan', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Plan_Estudio',
                'managed': False,
            },
        ),
    ]
