# Usa una imagen base de Python con Debian
FROM python:3.11-slim-bullseye

# Establece el directorio de trabajo
WORKDIR /workspaces/ISDMEstadodeCuenta

# Asegura la instalación de dependencias necesarias para mysqlclient
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*