# Generated by Django 5.2.8 on 2025-11-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('rol', models.CharField(default='Alumno', max_length=20)),
            ],
            options={
                'db_table': 'Alumno',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Carrera',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.IntegerField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimiento', models.DateField()),
                ('recargo_importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fk_id_carrera', models.ForeignKey(db_column='FK_id_carrera', on_delete=django.db.models.deletion.CASCADE, to='mi_app.carrera')),
            ],
            options={
                'db_table': 'Cuota',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id_comprobante', models.IntegerField(primary_key=True, serialize=False)),
                ('nro_comprobante', models.CharField(max_length=50)),
                ('fecha_emision', models.DateTimeField()),
                ('fk_id_pago', models.ForeignKey(db_column='FK_id_pago', on_delete=django.db.models.deletion.CASCADE, to='mi_app.pago')),
            ],
            options={
                'db_table': 'Comprobante',
            },
        ),
        migrations.CreateModel(
            name='PlanCuotasAlumno',
            fields=[
                ('id_plan', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('fk_id_alumno', models.ForeignKey(db_column='FK_id_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='planes_cuotas', to='mi_app.alumno')),
                ('fk_id_cuota', models.ForeignKey(db_column='FK_id_cuota', on_delete=django.db.models.deletion.CASCADE, to='mi_app.cuota')),
            ],
            options={
                'db_table': 'Plan_Cuotas_Alumno',
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='fk_id_plan',
            field=models.ForeignKey(db_column='FK_id_plan', on_delete=django.db.models.deletion.CASCADE, to='mi_app.plancuotasalumno'),
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id_plan', models.IntegerField(primary_key=True, serialize=False)),
                ('fk_id_alumno', models.ForeignKey(db_column='FK_id_alumno', on_delete=django.db.models.deletion.CASCADE, to='mi_app.alumno')),
                ('fk_id_carrera', models.ForeignKey(db_column='FK_id_carrera', on_delete=django.db.models.deletion.CASCADE, to='mi_app.carrera')),
            ],
            options={
                'db_table': 'Plan_Estudio',
            },
        ),
    ]
